### ISSUE TITLE
gopherwx_1  | standard_init_linux.go:190: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by godorizzi** [chrissnell/remoteweather#4]
Hi,

I am trying to use what looks to be a really promising piece of software on a RPI 3.
I followed the README.md but, after starting the service and running journalctl -u gopherwx -f this is what I got:
 
`apr 29 01:44:35 rpi systemd[1]: gopherwx.service: Service hold-off time over, scheduling restart.
apr 29 01:44:35 rpi systemd[1]: Stopped Dockerized Gopherwx.
apr 29 01:44:35 rpi systemd[1]: Starting Dockerized Gopherwx...
apr 29 01:44:49 rpi docker-compose[19599]: Going to remove gopherwx_gopherwx_1
apr 29 01:44:49 rpi docker-compose[19599]: Are you sure? [yN]
apr 29 01:44:55 rpi docker-compose[19610]: Pulling gopherwx (chrissnell/gopherwx:latest)...
apr 29 01:44:57 rpi docker-compose[19610]: latest: Pulling from chrissnell/gopherwx
apr 29 01:44:57 rpi docker-compose[19610]: Digest: sha256:61e6c0af703c3ea3e219b524f528805d0d832add921ffb93149f51301e2fa411
apr 29 01:44:57 rpi docker-compose[19610]: Status: Image is up to date for chrissnell/gopherwx:latest
apr 29 01:44:57 rpi systemd[1]: Started Dockerized Gopherwx.
apr 29 01:45:04 rpi docker-compose[19622]: Recreating gopherwx_gopherwx_1 ...
apr 29 01:45:06 rpi docker-compose[19622]: [85B blob data]
apr 29 01:45:06 rpi docker-compose[19622]: gopherwx_1  | standard_init_linux.go:190: exec user process caused "exec format error"
apr 29 01:45:06 rpi docker-compose[19622]: gopherwx_gopherwx_1 exited with code 1
apr 29 01:45:06 rpi docker-compose[19622]: 
`
Do you have any suggestion? 

Thank you in advance.

**Comment by godorizzi** [comment]
Nevermind, I just cloned the repo and built it from scratch. gopherwx is now running, I will now try to figure out how to configure InflxDB.

**Comment by chrissnell** [comment]
Sorry, the Docker image is built for x64, not ARM.  That's why you were seeing this.  The solution is, as you noticed, to rebuild it on an ARM platform.

**Comment by fsegouin** [comment]
@godorizzi Do you mind sharing instructions about how to build the image from scratch? Or share your armhf image? Thanks!
