### ISSUE TITLE
Compile for ARM

### ISSUE THREAD

**Issue by fsegouin** [chrissnell/remoteweather#6]
Hi, I'm trying to compile the gopherwx executable to rebuild a docker image for armhf (raspberry pi 4) and I'm not sure as to what arguments I should use?

I tried using `go build` but it fails with the version of the influxdb client not being able to be downloaded anymore. I tried updating manually to `influxdb-client-go` but then there's an error, which makes me think the code isn't compatible with the latest version of the influxdb client anymore. 

Thanks for your help!

**Comment by fsegouin** [comment]
I created a Dockerfile that compiles the binary on top of golang:alpine if anyone is wondering how to achieve this.

**Comment by chrissnell-okta** [comment]
Sure, send PR?  It's been a while since I've worked on this project.  Happy to take improvements if you have them.
